### ISSUE TITLE
Getting empty output on GEOJSON -> GPX

### ISSUE THREAD

**Issue by amenk** [Yermo/geoPHPwithFeatures#18]
I am getting an "empty" (no features in it) GPX output on the attached file.

[654.geojson.txt](https://github.com/Yermo/geoPHPwithFeatures/files/1934811/654.geojson.txt)

    php geo_convert.php --input-path=../../654.geojson --input-format=geojson --output-path=../../654.gpx --output-format=gpx

**Comment by amenk** [comment]
Problem seems to be in 1a3e867733ef096b14f66b76652c04233c59829f

**Comment by amenk** [comment]
I think in https://github.com/Yermo/geoPHPwithFeatures/commit/1a3e867733ef096b14f66b76652c04233c59829f#diff-ec74daab0c039471443e93539b60630aR1097 you meant to write `!=`

**Comment by amenk** [comment]
There should be a handling for cases where there is no meta data ... And the function may be written more elegant with a custom array sort  `uasort`

**Comment by Yermo** [comment]
Want to make a pull request for it?
